name: Build Goodbirds Maps (multi-city)

on:
  schedule:
    - cron: "0 16 * * *"
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    # Job-level env: define this ONCE
    env:
      LOGO_BASENAME: goodbirds_logo_text.png
      MAP_LOGO_URL: https://goodbirds.org/goodbirds_logo_text.png

    strategy:
      matrix:
        city:
          - slug: cambridge
            title: "Cambridge, MA & Vicinity"
            center_lat: "42.378500"
            center_lon: "-71.115600"
            ring_kms: "5,10,15,20"
            default_radius_km: "20"
            maps_subdir: "cambridge"
            latest_href: "/maps/cambridge/latest.html"
          - slug: north-cambridge
            title: "North Cambridge, MA and Vicinity"
            center_lat: "42.400973"
            center_lon: "-71.135970"
            ring_kms: "5,10,15"
            default_radius_km: "15"
            maps_subdir: "north-cambridge"
            latest_href: "/maps/north-cambridge/latest.html"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure docs directories exist
        run: |
          mkdir -p docs/maps/${{ matrix.city.maps_subdir }}
          mkdir -p docs/${{ matrix.city.slug }}

      - name: Copy logo into docs if present at repo root
        run: |
          if [ -f "${{ env.LOGO_BASENAME }}" ]; then
            cp "${{ env.LOGO_BASENAME }}" "docs/${{ env.LOGO_BASENAME }}"
          fi

      - name: Build map for ${{ matrix.city.title }}
        env:                       # step-level env is fine
          EBIRD_API_KEY: ${{ secrets.EBIRD_API_KEY }}
          OUTPUT_DIR: docs/maps/${{ matrix.city.maps_subdir }}
          MAP_LOGO_FILE: ${{ github.workspace }}/docs/goodbirds_logo_text.png
          MAP_LOGO_URL: ${{ env.MAP_LOGO_URL }}
          ARCHIVE_URL: https://goodbirds.org/${{ matrix.city.slug }}/archive.html
          MAP_MAIN_TITLE: ${{ matrix.city.title }}
          CENTER_LAT: ${{ matrix.city.center_lat }}
          CENTER_LON: ${{ matrix.city.center_lon }}
          DEFAULT_RADIUS_KM: ${{ matrix.city.default_radius_km }}
          BACK_DAYS: "2"
          MAX_RESULTS: "200"
          ZOOM_START: "11"
          RING_KMS: ${{ matrix.city.ring_kms }}
        run: |
          python scripts/build_map.py

      - name: Write /${{ matrix.city.slug }}/index.html redirect to latest map
        env:                       # only ONE env for this step
          LATEST: ${{ matrix.city.latest_href }}
        run: |
          cat > docs/${{ matrix.city.slug }}/index.html <<'HTML'
          <!doctype html>
          <html>
          <head>
          <meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=${LATEST}">
          <title>Redirecting…</title>
          </head>
          <body>
          <p>Redirecting to the latest Goodbirds map…</p>
          </body>
          </html>
          HTML

      - name: Build /${{ matrix.city.slug }}/archive.html (weekday labels)
        env:
          GIT_SHA: ${{ github.sha }}
          CITY_SLUG: ${{ matrix.city.slug }}
          CITY_TITLE: ${{ matrix.city.title }}
          MAPS_SUBDIR: ${{ matrix.city.maps_subdir }}
        run: |
          python - <<'PY'
          # ... your Python block unchanged ...
          PY

      - name: Commit and push city outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Build maps for ${{ matrix.city.title }} into docs/maps/${{ matrix.city.maps_subdir }} and update pages"
            git push
          else
            echo "No changes to commit."
          fi

  landing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write landing page with both cities
        run: |
          python - <<'PY'
          # ... your Python block unchanged ...
          PY
