name: Post map screenshot to Bluesky

on:
  schedule:
    - cron: "0 10 * * *"   # 06:00 ET during Daylight Time
    - cron: "0 11 * * *"   # 06:00 ET during Standard Time
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Only run at 06:00 America/New_York
        run: |
          if [ "$(TZ=America/New_York date +%H)" != "06" ]; then
            echo "Not 06:00 in New York. Exiting."
            exit 0
          fi

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Post rotating screenshot to Bluesky
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}

          # Optional tuning
          # VIEWPORT_W: "1400"
          # VIEWPORT_H: "900"
          # WAIT_MS: "6000"

          # Optional rotation tweak
          # ROTATION_OFFSET: "0"

          # Set DRY_RUN=1 to test without posting
          # DRY_RUN: "1"
        run: |
          python scripts/capture_and_post_bsky.py
